#from helixcore.server.exceptions import ActionNotAllowedError
from helixcore.db.wrapper import ObjectNotFound


class HelixauthError(Exception):
    pass
